name: Learn basics of GitHub Action

on:
  push:
    branches:
      - main

jobs:
  mavenBuild:
    runs-on: ubuntu-latest

    container:
      image: maven:latest
      
    steps:
      
      - name: Run Maven clean install
        run: mvn clean install